import './App.css'

function App() {
  return (
    <main>
      <nav className="nav shell" aria-label="Main navigation">
        <div className="profile-sidebar">
          <span className="profile-photo">
            <img src="/profile-photo.jpeg" alt="Kanhu Charan Barad" onError={(event) => { event.currentTarget.style.display = 'none' }} />
            <span className="profile-initials">KCB</span>
          </span>
          <span className="profile-details"><strong>Kanhu Charan Barad</strong><small>Java Backend Developer</small><small>Bengaluru, Karnataka</small></span>
        </div>
        <div className="nav-links"><a href="#top">Home</a><a href="#work">About</a><a href="#skills">Skills</a><a href="#systems">Portfolio</a><a href="#education">Education</a><a href="#contact">Contact</a></div>
        <a className="status" href="mailto:kanhubarad74@gmail.com"><span className="status-dot" /> Hire me</a>
      </nav>

      <section className="hero shell" id="top"><div className="hero-copy"><p className="eyebrow"><span>Hello!</span> Java Backend Developer / Bengaluru</p><h1>I am <em>Kanhu</em><br />Charan Barad</h1><p className="intro">I am a Java Backend Developer with 3+ years of experience building scalable APIs, microservices, event-driven systems, and AI-powered applications.</p><div className="hero-actions"><a className="button button-primary" href="#systems">See my portfolio <span>↗</span></a><a className="text-link" href="#contact">Let's connect <span>↗</span></a></div></div><div className="hero-aside"><span className="hero-photo"><img src="/profile-photo.jpeg" alt="Kanhu Charan Barad" onError={(event) => { event.currentTarget.style.display = 'none' }} /><span className="hero-photo-fallback">KCB</span></span><div className="hero-note"><span>Currently building</span><strong>Reliable systems<br />with a human edge.</strong></div></div></section>

      <section className="signal-bar"><div className="shell signal-grid"><div><strong>3+</strong><span>years shipping<br />production software</span></div><div><strong>150<span>+</span></strong><span>DSA problems<br />solved</span></div><div><strong>01</strong><span>Rising Star<br />Award</span></div><div className="signal-quote">“Make it work.<br /><em>Then make it last.</em>”</div></div></section>

      <section className="section shell" id="work"><div className="section-heading"><p className="eyebrow"><span>02</span> The path so far</p><h2>Experience that<br /><em>compounds.</em></h2></div><div className="timeline"><article className="timeline-item current"><div className="timeline-meta"><span>Feb 2026 — Now</span><span className="current-label">Current</span></div><div className="timeline-content"><h3>Java Backend Developer</h3><p className="company">Hutech Solutions <span>×</span> Client: Serko / GetThere</p><p>Contributing to a B2B travel booking platform for hotels, flights, and cabs. Building Spring Boot endpoints, improving data flows, and collaborating across UI, design, and backend teams.</p><div className="tags"><span>Java</span><span>Spring Boot</span><span>Travel tech</span></div></div></article><article className="timeline-item"><div className="timeline-meta"><span>Jan 2024 — Feb 2026</span></div><div className="timeline-content"><h3>Java Backend Developer</h3><p className="company">Hutech Solutions <span>×</span> Client: DesignCafe</p><p>Engineered scalable services and secure REST APIs with Java 17, Spring Boot, JPA, and Hibernate. Built Kafka workflows, Redis caching, and database-driven features across development and production.</p><div className="tags"><span>Microservices</span><span>Kafka</span><span>AWS</span><span>Docker</span></div></div></article></div></section>

      <section className="systems-section" id="systems"><div className="shell project-layout"><div className="section-heading light"><p className="eyebrow"><span>03</span> Featured system</p><h2>One idea.<br /><em>Many moving parts.</em></h2><p className="section-lede">An airline booking platform designed as a set of dependable, independent services. Built to handle the happy path and everything around it.</p><a className="button button-lime" href="mailto:kanhubarad74@gmail.com?subject=Airline%20Booking%20System">Discuss the architecture <span>↗</span></a></div><div className="system-card"><div className="system-top"><span>PROJECT / 001</span><span>JAVA 17</span></div><div className="system-visual"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="core-node">AIR<br /><small>BOOKING</small></div><div className="node node-flight">FLIGHT</div><div className="node node-pay">PAYMENT</div><div className="node node-notify">NOTIFY</div><div className="node node-ai">AI / RAG</div></div><div className="system-bottom"><p>Flight · Booking · Payment · Notification</p><div className="stack-row"><span>Kafka</span><span>Redis</span><span>Resilience4j</span><span>Spring AI</span></div></div></div></div></section>

      <section className="section shell skills-section" id="skills"><div className="section-heading"><p className="eyebrow"><span>04</span> The toolkit</p><h2>Deep where it<br /><em>matters.</em></h2></div><div className="skills-list"><div className="skill-row"><span className="skill-number">01</span><h3>Backend engineering</h3><p>Java 8 / 11 / 17, Spring Boot, Spring Cloud, REST APIs, Microservices, JPA, Hibernate, Design Patterns, System Design</p></div><div className="skill-row"><span className="skill-number">02</span><h3>Data & messaging</h3><p>MySQL, PostgreSQL, MongoDB, SQL optimization, Apache Kafka, event-driven architecture, asynchronous processing, Redis</p></div><div className="skill-row"><span className="skill-number">03</span><h3>AI, thoughtfully applied</h3><p>LLMs, RAG, prompt engineering, embeddings, semantic search, OCR, AI agents, Agentic AI, Spring AI</p></div><div className="skill-row"><span className="skill-number">04</span><h3>Ship & sustain</h3><p>AWS, Docker, Kubernetes, Jenkins, CI/CD, Git, Maven, Linux, Kibana, JUnit, RCA, production support</p></div></div></section>

      <section className="education-section section shell" id="education"><div className="section-heading"><p className="eyebrow"><span>05</span> Education</p><h2>Where the<br /><em>foundation began.</em></h2></div><article className="education-card"><span className="education-year">2018 — 2022</span><h3>Bachelor of Technology</h3><p className="education-field">Mechanical Engineering</p><p>Gandhi Institute For Technology</p></article></section>

      <section className="contact-section" id="contact"><div className="shell contact-layout"><div><p className="eyebrow"><span>06</span> Open channel</p><h2>Let's make<br /><em>something durable.</em></h2></div><div className="contact-side"><p>Have a backend problem worth solving, a product to scale, or a team building for the long run? I’d like to hear about it.</p><a className="contact-email" href="mailto:kanhubarad74@gmail.com">kanhubarad74@gmail.com <span>↗</span></a><div className="social-links"><a href="https://github.com/KanhuCharan67" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://www.linkedin.com/in/kanhu25" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="tel:+917789009167">+91 77890 09167</a></div></div></div></section>
      <footer className="shell footer"><span>© 2026 Kanhu Charan Barad</span><span>Designed & built with intent <b>✦</b></span></footer>
    </main>
  )
}

export default App
